import os

PEER_NID_SEPARATOR = ','
PYTHON_PATH_SEPARATOR = '.'
NODE_ADDRESSES_FILE_PATH = os.path.join('node_addresses.yml')
CONNECTION_PARAMETERS_FILE_PATH = os.path.join('connection_parameters.yml')
USER_NODE_FILES_MODULE = 'user_node_files'
BUFFER_SIZE = 65536
DEFAULT_SEND_DELAY = 0

NODE_CONNECTIONS_PARAMETERS_SUCCESS_RATE = 'successRate'
NODE_CONNECTIONS_PARAMETERS_DELAY_DISTRIBUTION = 'delayDistribution'
NODE_CONNECTIONS_PARAMETERS_DELAY_DISTRIBUTION_PARAMETERS = 'delayDistributionParameters'
